---
title: "penguins.assignment"
author: "Matilda Rousham"
date: "2022-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setting working directory, loading libraries and loading data

```{r}
# Set working directory
setwd("/Users/matildarousham/Documents/penguin_assessment")

# Load libraries/packages
source("functions/libraries.r")

# Load functions 
source("functions/cleaning.r")
source("functions/plotting.r")

# Load data
penguins_raw <- read.csv("/Users/matildarousham/Documents/penguin_assessment/data_raw/penguins_raw.csv") 

```

## Cleaning data

```{r}
# Use cleaning function on raw data
## Removes columns "Comments" and columns beginning with "Delta"
## Removes observations with missing values 
penguin_clean <- cleaning(penguins_raw)

# Save clean data in new folder
write.csv(penguin_clean, "data_clean/penguin_clean.csv")

# Use function to remove NAs from dataset 
penguin_cleaner <- remove_na(penguin_clean)

# Save "cleaner" data in a new folder 
write.csv(penguin_cleaner, "data_clean/penguin_cleaner.csv")
```

## Carry out a statistical test 

```{r}
# Plot scatter plot of data to see raw data
ggplot(penguin_cleaner, 
       aes(x = flipper_length_mm,
           y = body_mass_g)) +
  geom_point()

# Create linear regression
penguin_mod <- lm(body_mass_g ~ flipper_length_mm, penguin_cleaner)

# Summary of linear regression model
summary(penguin_mod)

# Run diagnostic plots for assumptions
plot(penguin_mod, which = 1)
plot(penguin_mod, which = 2)

# Plot linear regression on scatter plot 
ggplot(penguin_cleaner, aes(x = flipper_length_mm, y = body_mass_g)) +
geom_point() +
geom_smooth(method = "lm")

# Use function to plot the linear regression (with improved aesthetics)
mass_length_lm <- plot_regression(penguin_cleaner)

# Look at figure
mass_length_lm
```

## Save figures using function "save_lm_plot.."

```{r}
# Save figure suitable for a report
save_lm_plot_png(penguin_cleaner, 
                      "figures/fig01_report.png", 
                      size = 15, res = 600, scaling = 1)

# Save figure suitable for a presentation
save_lm_plot_png(penguin_cleaner, 
                      "figures/fig01_presentation.png", 
                      size = 20, res = 600, scaling = 1.3)

# Save figure suitable for a poster
save_lm_plot_png(penguin_cleaner, 
                      "figures/fig01_poster.png", 
                      size = 30, res = 600, scaling = 2)

# Save figure as a vector
save_lm_plot_svg(penguin_cleaner, 
                      "figures/fig01_vector.svg", 
                      size = 15, scaling = 1)
```







